export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const SIGNUP = 'SIGNUP'
export const GET_USER = 'GET_USER'
export const GET_ENTRIES = 'GET_ENTRIES'
export const DELETE_ENTRY = 'DELETE_ENTRY'
export const EDIT_ENTRY = 'EDIT_ENTRY'
export const SAVE_ENTRY = 'SAVE_ENTRY'